import type { Artist, Release, JournalEntry, NHBEvent, Track } from "./types"

// Placeholder audio (royalty-free samples) used across the player.
const AUDIO = [
  "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
  "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
  "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
  "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
  "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
]

function track(id: string, title: string, duration: string, i = 0): Track {
  return { id, title, duration, audioUrl: AUDIO[i % AUDIO.length] }
}

export const artists: Artist[] = [
  {
    slug: "velvet-static",
    name: "Velvet Static",
    type: "member",
    role: "Producer / Live",
    location: "Berlin, DE",
    tagline: "Corroded ambient techno built from tape hiss and field noise.",
    bio: [
      "Velvet Static is the recording alias of a producer working between disused industrial spaces and a small tape studio in Neukölln. The project began as a series of unlabeled cassettes passed between friends.",
      "The sound sits between ambient and functional club music — long, decaying pads pushed through failing hardware, rhythm sections that arrive late and leave early. Every release is treated as a document rather than a product.",
    ],
    portrait: "/images/velvet-static-portrait.png",
    hero: "/images/velvet-static-hero.png",
    socials: [
      { label: "Instagram", href: "#" },
      { label: "Bandcamp", href: "#" },
      { label: "SoundCloud", href: "#" },
    ],
    releaseSlugs: ["dead-air", "north-corridor"],
    unreleased: [
      track("vs-u1", "Untitled (Cellar)", "6:12", 0),
      track("vs-u2", "Iron Loop", "4:48", 1),
      track("vs-u3", "Blue Hour Dub", "7:03", 2),
    ],
    videos: [
      { id: "vs-v1", title: "Live at Halle Null", year: "2025", thumbnail: "/images/velvet-static-hero.png" },
    ],
    news: [
      { id: "vs-n1", date: "2026.02.11", title: "New 12\" pressed on recycled vinyl, out this spring." },
      { id: "vs-n2", date: "2025.11.03", title: "Featured on the NHB winter transmission." },
    ],
    merch: [
      { id: "vs-m1", name: "Dead Air — Cassette", price: "€12", image: "/images/release-dead-air.png" },
      { id: "vs-m2", name: "Static Tee (Black)", price: "€35", image: "/images/velvet-static-portrait.png" },
    ],
    eventSlugs: ["nhb-transmission-07"],
    photos: ["/images/velvet-static-hero.png", "/images/velvet-static-portrait.png"],
    press: [
      { id: "vs-p1", outlet: "Fault Lines", quote: "The most convincing case for ruin as a musical value in years.", year: "2025" },
    ],
  },
  {
    slug: "koji-nd",
    name: "Koji ND",
    type: "member",
    role: "Composer / DJ",
    location: "Tokyo, JP",
    tagline: "Weightless club music for rooms that never fully empty.",
    bio: [
      "Koji ND composes for the hours after a night has technically ended. Drawing on deconstructed club, dub and early trance, the music is built to feel suspended — always about to resolve.",
      "A resident of a roving Tokyo party series before joining no.holds.barred, Koji treats DJing and production as one continuous practice.",
    ],
    portrait: "/images/koji-nd-portrait.png",
    hero: "/images/koji-nd-portrait.png",
    socials: [
      { label: "Instagram", href: "#" },
      { label: "Bandcamp", href: "#" },
    ],
    releaseSlugs: ["weightless"],
    unreleased: [track("kn-u1", "Afterimage", "5:20", 3), track("kn-u2", "Low Ceiling", "6:41", 4)],
    videos: [{ id: "kn-v1", title: "Boiler Session — Shibuya", year: "2025", thumbnail: "/images/koji-nd-portrait.png" }],
    news: [{ id: "kn-n1", date: "2026.01.20", title: "Debut LP announced for autumn." }],
    merch: [{ id: "kn-m1", name: "Weightless — Vinyl", price: "€28", image: "/images/release-weightless.png" }],
    eventSlugs: ["nhb-transmission-07"],
    photos: ["/images/koji-nd-portrait.png", "/images/koji-nd-portrait.png"],
    press: [{ id: "kn-p1", outlet: "Static Digest", quote: "Club music dissolved into pure suggestion.", year: "2025" }],
  },
  {
    slug: "mara-voss",
    name: "Mara Voss",
    type: "member",
    role: "Vocalist / Writer",
    location: "London, UK",
    tagline: "Avant-pop that treats the voice as an unstable instrument.",
    bio: [
      "Mara Voss writes songs that fold in on themselves — pop structures rebuilt with the wrong proportions. Her work moves between spoken word, close-mic'd vocals and processed choirs.",
      "Trained in classical composition before abandoning it, she describes her records as 'diaries with the pages torn out of order.'",
    ],
    portrait: "/images/mara-voss-portrait.png",
    hero: "/images/mara-voss-portrait.png",
    socials: [
      { label: "Instagram", href: "#" },
      { label: "Bandcamp", href: "#" },
      { label: "Website", href: "#" },
    ],
    releaseSlugs: ["paper-saints"],
    unreleased: [track("mv-u1", "Hymn for No One", "3:58", 1), track("mv-u2", "Glass Diary", "4:26", 2)],
    videos: [{ id: "mv-v1", title: "Paper Saints (Live Take)", year: "2025", thumbnail: "/images/mara-voss-portrait.png" }],
    news: [{ id: "mv-n1", date: "2026.02.02", title: "Short film companion piece in production." }],
    merch: [{ id: "mv-m1", name: "Paper Saints — Zine + CD", price: "€22", image: "/images/release-paper-saints.png" }],
    eventSlugs: ["voss-live-london"],
    photos: ["/images/mara-voss-portrait.png", "/images/mara-voss-portrait.png"],
    press: [{ id: "mv-p1", outlet: "The Quiet Ear", quote: "A songwriter dismantling the form she clearly loves.", year: "2025" }],
  },
  {
    slug: "the-late-hours",
    name: "The Late Hours",
    type: "member",
    role: "Band",
    location: "New York, US",
    tagline: "Post-punk recorded in one room, first takes only.",
    bio: [
      "The Late Hours are a trio who record live to tape with almost no overdubs. The result is brittle, urgent post-punk — all edges and negative space.",
      "They surfaced through a run of unannounced loft shows and remain deliberately hard to find online.",
    ],
    portrait: "/images/late-hours-portrait.png",
    hero: "/images/late-hours-portrait.png",
    socials: [
      { label: "Instagram", href: "#" },
      { label: "Bandcamp", href: "#" },
    ],
    releaseSlugs: ["first-takes"],
    unreleased: [track("lh-u1", "Wire", "2:51", 0), track("lh-u2", "Curfew", "3:33", 3)],
    videos: [{ id: "lh-v1", title: "Loft Show No.4", year: "2024", thumbnail: "/images/late-hours-portrait.png" }],
    news: [{ id: "lh-n1", date: "2025.12.10", title: "First Takes sold out on first pressing." }],
    merch: [{ id: "lh-m1", name: "First Takes — LP", price: "€26", image: "/images/release-first-takes.png" }],
    eventSlugs: ["nhb-transmission-07"],
    photos: ["/images/late-hours-portrait.png", "/images/late-hours-portrait.png"],
    press: [{ id: "lh-p1", outlet: "Nightshift", quote: "Three people, one room, zero pretense.", year: "2024" }],
  },
]

const affiliateSeed: Array<Partial<Artist> & { slug: string; name: string; role: string; location: string; tagline: string }> = [
  { slug: "lowtide", name: "Lowtide", role: "Producer", location: "Lisbon, PT", tagline: "Salt-worn dub techno recorded near the water." },
  { slug: "ghost-notation", name: "Ghost Notation", role: "Duo", location: "Manchester, UK", tagline: "Broken jungle stitched from library records." },
  { slug: "ivy-kwon", name: "Ivy Kwon", role: "Cellist / Producer", location: "Seoul, KR", tagline: "Chamber electronics for empty concert halls." },
  { slug: "static-bloom", name: "Static Bloom", role: "Vocalist", location: "Montreal, CA", tagline: "Shoegaze pop drowned in reverb and doubt." },
  { slug: "deniz-aran", name: "Deniz Aran", role: "DJ / Producer", location: "Istanbul, TR", tagline: "Psychedelic folk sampled into club tools." },
  { slug: "patch", name: "Patch", role: "Modular Artist", location: "Rotterdam, NL", tagline: "Generative patches that never repeat a bar." },
  { slug: "marlowe", name: "Marlowe", role: "Rapper / Poet", location: "Chicago, US", tagline: "Spoken word over collapsing soul loops." },
  { slug: "vhs-priest", name: "VHS Priest", role: "Producer", location: "Mexico City, MX", tagline: "Tape-warped ballads for a haunted arcade." },
]

export const affiliates: Artist[] = affiliateSeed.map((a, i) => ({
  slug: a.slug,
  name: a.name,
  type: "affiliate",
  role: a.role,
  location: a.location,
  tagline: a.tagline,
  bio: [
    `${a.name} is not an official member of no.holds.barred. They appear here because we keep returning to their work — an artist we are listening to closely and want to point toward.`,
    "This page is a recommendation, not a contract. Follow the links, buy the records, go to the shows.",
  ],
  portrait: `/images/affiliate-${a.slug}.png`,
  hero: `/images/affiliate-${a.slug}.png`,
  socials: [
    { label: "Bandcamp", href: "#" },
    { label: "Instagram", href: "#" },
  ],
  releaseSlugs: [],
  unreleased: [track(`${a.slug}-u1`, "Selected Track", "4:10", i)],
  videos: [],
  news: [],
  merch: [],
  eventSlugs: [],
  photos: [`/images/affiliate-${a.slug}.png`],
  press: [],
}))

export const releases: Release[] = [
  {
    slug: "dead-air",
    title: "Dead Air",
    artistSlug: "velvet-static",
    artistName: "Velvet Static",
    type: "EP",
    date: "2026-03-14",
    year: "2026",
    catalog: "NHB-011",
    artwork: "/images/release-dead-air.png",
    description: [
      "Four studies in decay, recorded to a single reel of tape that was then partially erased.",
      "Dead Air is the sound of a signal refusing to fully disappear.",
    ],
    tracklist: [
      track("da-1", "Dead Air", "6:44", 0),
      track("da-2", "Corridor", "5:12", 1),
      track("da-3", "Erasure", "7:20", 2),
      track("da-4", "Blue Hour", "6:01", 3),
    ],
  },
  {
    slug: "weightless",
    title: "Weightless",
    artistSlug: "koji-nd",
    artistName: "Koji ND",
    type: "Album",
    date: "2025-10-02",
    year: "2025",
    catalog: "NHB-009",
    artwork: "/images/release-weightless.png",
    description: ["A full-length suite for the last hour of the night, mixed to play as one continuous piece."],
    tracklist: [
      track("w-1", "Afterimage", "5:20", 3),
      track("w-2", "Low Ceiling", "6:41", 4),
      track("w-3", "Suspended", "7:15", 0),
      track("w-4", "Exit Music", "8:02", 1),
    ],
  },
  {
    slug: "paper-saints",
    title: "Paper Saints",
    artistSlug: "mara-voss",
    artistName: "Mara Voss",
    type: "Album",
    date: "2025-06-20",
    year: "2025",
    catalog: "NHB-006",
    artwork: "/images/release-paper-saints.png",
    description: ["Eleven songs about faith, memory and mishearing. Accompanied by a hand-assembled zine."],
    tracklist: [
      track("ps-1", "Paper Saints", "3:58", 1),
      track("ps-2", "Glass Diary", "4:26", 2),
      track("ps-3", "Hymn for No One", "3:12", 3),
      track("ps-4", "Torn Pages", "5:04", 4),
    ],
  },
  {
    slug: "first-takes",
    title: "First Takes",
    artistSlug: "the-late-hours",
    artistName: "The Late Hours",
    type: "Album",
    date: "2025-01-31",
    year: "2025",
    catalog: "NHB-004",
    artwork: "/images/release-first-takes.png",
    description: ["Recorded live to tape over two nights. No overdubs. What you hear is the room."],
    tracklist: [
      track("ft-1", "Wire", "2:51", 0),
      track("ft-2", "Curfew", "3:33", 3),
      track("ft-3", "Nightshift", "4:10", 1),
      track("ft-4", "Last Train", "3:47", 2),
    ],
  },
  {
    slug: "north-corridor",
    title: "North Corridor",
    artistSlug: "velvet-static",
    artistName: "Velvet Static",
    type: "Single",
    date: "2024-09-13",
    year: "2024",
    catalog: "NHB-002",
    artwork: "/images/release-north-corridor.png",
    description: ["The first transmission from Velvet Static under the no.holds.barred banner."],
    tracklist: [track("nc-1", "North Corridor", "7:41", 2), track("nc-2", "North Corridor (Reduction)", "5:18", 0)],
  },
  {
    slug: "transmission-one",
    title: "Transmission One",
    artistSlug: "various",
    artistName: "Various Artists",
    type: "Compilation",
    date: "2024-04-01",
    year: "2024",
    catalog: "NHB-001",
    artwork: "/images/release-transmission-one.png",
    description: ["The inaugural compilation that defined the collective's first year. A statement of intent."],
    tracklist: [
      track("t1-1", "Velvet Static — Iron Loop", "4:48", 1),
      track("t1-2", "Koji ND — Suspended", "7:15", 0),
      track("t1-3", "Mara Voss — Torn Pages", "5:04", 4),
      track("t1-4", "The Late Hours — Wire", "2:51", 3),
    ],
  },
]

export const journal: JournalEntry[] = [
  {
    slug: "inside-velvet-static-tape-room",
    title: "Inside Velvet Static's Tape Room",
    category: "Studio Visit",
    excerpt: "A morning among failing machines in a Neukölln basement, where decay is a compositional tool.",
    author: "Editorial",
    date: "2026.02.18",
    readTime: "8 min",
    cover: "/images/journal-tape-room.png",
    body: [
      "The room is smaller than you expect. Tape spools line one wall; a single window throws grey light across a mixing desk that has clearly survived several floods.",
      "\"I don't fix anything that breaks in an interesting way,\" Velvet Static says, threading a reel that has already been recorded over twice.",
      "What follows is less an interview than a demonstration — of patience, of listening, of letting a signal fall apart on its own terms.",
    ],
  },
  {
    slug: "koji-nd-on-the-last-hour",
    title: "Koji ND on the Last Hour of the Night",
    category: "Interview",
    excerpt: "The Tokyo composer talks about writing for rooms that never fully empty.",
    author: "Editorial",
    date: "2026.01.29",
    readTime: "12 min",
    cover: "/images/journal-koji-interview.png",
    body: [
      "We meet at 5am, which Koji insists is the only honest time to discuss the music.",
      "\"Everyone writes for the peak,\" he says. \"I'm interested in the part nobody remembers — when the room is deciding whether to stay.\"",
    ],
  },
  {
    slug: "paper-saints-release-story",
    title: "The Making of Paper Saints",
    category: "Release Story",
    excerpt: "How Mara Voss turned a year of misheard prayers into an album and a zine.",
    author: "Editorial",
    date: "2025.06.19",
    readTime: "10 min",
    cover: "/images/journal-paper-saints.png",
    body: [
      "The album began as marginalia — notes scrawled in the backs of borrowed books.",
      "\"I kept mishearing things,\" Voss says. \"Eventually the mishearings were more interesting than what was actually said.\"",
    ],
  },
  {
    slug: "night-photography-transmission-06",
    title: "Transmission 06 — In Photographs",
    category: "Photography",
    excerpt: "A photo essay from the collective's most recent all-night event.",
    author: "Editorial",
    date: "2025.11.22",
    readTime: "4 min",
    cover: "/images/journal-photo-essay.png",
    body: [
      "No captions. No names. Just the room, the fog, and the hours between midnight and the first train.",
    ],
  },
  {
    slug: "why-we-keep-affiliates",
    title: "Why We Keep an Affiliates List",
    category: "Essay",
    excerpt: "On curation as generosity, and the difference between a roster and a recommendation.",
    author: "no.holds.barred",
    date: "2025.09.05",
    readTime: "6 min",
    cover: "/images/journal-essay.png",
    body: [
      "A label is a small thing. A scene is larger than any label can hold.",
      "The affiliates list is how we admit that most of the music we love is not ours to release.",
    ],
  },
  {
    slug: "winter-transmission-playlist",
    title: "Winter Transmission — A Playlist",
    category: "Playlist",
    excerpt: "Two hours of what the collective has been playing in the cold months.",
    author: "Editorial",
    date: "2025.12.01",
    readTime: "2 min",
    cover: "/images/journal-playlist.png",
    body: ["Best played loud, in the dark, alone or with two people maximum."],
  },
]

export const events: NHBEvent[] = [
  {
    slug: "nhb-transmission-07",
    title: "NHB Transmission 07",
    date: "2026-04-18",
    dateLabel: "18 APR 2026",
    venue: "Halle Null",
    city: "Berlin",
    lineup: ["Velvet Static", "Koji ND", "The Late Hours", "Lowtide"],
    status: "upcoming",
    image: "/images/event-transmission-07.png",
    description: "An all-night transmission across two rooms. No phones on the floor. Doors at 23:00.",
  },
  {
    slug: "voss-live-london",
    title: "Mara Voss — Paper Saints Live",
    date: "2026-05-09",
    dateLabel: "09 MAY 2026",
    venue: "St. Leonard's",
    city: "London",
    lineup: ["Mara Voss", "Ivy Kwon"],
    status: "upcoming",
    image: "/images/event-voss-live.png",
    description: "A seated performance of Paper Saints in full, staged in a deconsecrated church.",
  },
  {
    slug: "nhb-transmission-06",
    title: "NHB Transmission 06",
    date: "2025-11-15",
    dateLabel: "15 NOV 2025",
    venue: "The Substation",
    city: "Amsterdam",
    lineup: ["Koji ND", "Deniz Aran", "Patch"],
    status: "past",
    image: "/images/event-transmission-06.png",
    description: "Our most recent all-night event. Documented in the Journal.",
  },
  {
    slug: "loft-show-04",
    title: "The Late Hours — Loft Show No.4",
    date: "2025-08-22",
    dateLabel: "22 AUG 2025",
    venue: "Undisclosed",
    city: "New York",
    lineup: ["The Late Hours"],
    status: "past",
    image: "/images/event-loft-show.png",
    description: "An unannounced loft show. Location shared by message only.",
  },
]

// Lookup helpers
export const allArtists = [...artists, ...affiliates]
export const getArtist = (slug: string) => allArtists.find((a) => a.slug === slug)
export const getRelease = (slug: string) => releases.find((r) => r.slug === slug)
export const getReleasesByArtist = (slug: string) => releases.filter((r) => r.artistSlug === slug)
export const getJournalEntry = (slug: string) => journal.find((j) => j.slug === slug)
export const getEvent = (slug: string) => events.find((e) => e.slug === slug)
export const getEventsBySlugs = (slugs: string[]) => events.filter((e) => slugs.includes(e.slug))
export const featuredArtist = artists[0]
export const latestRelease = releases[0]
